% Creation of vectors and matrices -- ECE 8 Fall 2022 Lecture 3
clear all;
close all;
clc

% define a 2D position vector
p_x = 2; % x component of the vector
p_y = 3; % y component of the vector
p = [p_x;p_y] % defines p vector as a column vector

% plot p
plot(p_x,p_y,'o') % plots p_y vs p_x with the marker o
axis([0 3 0 4]) % adjust the x axis to the range [0,3] and the y axis to the range [0,4]

% Back to the suggested exercise after Lecture 2

% Pick initial position 
p_x0 = 2;
p_y0 = 3;
p_0 = [p_x0;p_y0]; % position vector at time 1


% Suppose that the new position is generated by
% p^new_x = p_x + u_x
% p^new_y = p_y + u_y

u_x0 = 1; % pick the command input value for x
p_x1 = p_x0 + u_x0; % calculate new x position

u_y0 = 1;  % pick the command input value for y
p_y1 = p_y0 + u_y0; % calculate new y position

p_1 = [p_x1;p_y1]; % position vector at time 1

u_x1 = 3; % pick the command input value for x
p_x2 = p_x1 + u_x1; % calculate new x position

u_y1 = 0;  % pick the command input value for y
p_y2 = p_y1 + u_y1; % calculate new y position

p_2 = [p_x2;p_y2]; % position vector at time 1

% define a matrix collecting all of these data points
p_data = [p_0,p_1,p_2];

% Plot p_data
